// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbtbcpingwyuhbuofpkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idGJjcGluZ3d5dWhidW9mcGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTU5MjIsImV4cCI6MjA2MzgzMTkyMn0.hasm3iELBu_7g9c9TJXVuLj2yAi7mcv_Oz3C3aQ2MLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);